Fixes #111 for branch 1.x
plone/plone.app.querystring pull request #112
Opened 2022-07-07 14:40 UTC by erral

I just copied over the function `munge_search_terms` from https://github.com/plone/Products.CMFPlone/pull/3518

We are using the same plone.app.querystring version for both Plone 5.2.x and 6, so it is not possible to import from Products.CMFPlone and neither from plone.base if that function is ever moved to there.

Opinions? @petschki @jensens @mauritsvanrees

2022-07-07 14:40 UTC, mister-roboto commented
@erral thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2022-07-07 14:43 UTC, erral commented
@jenkins-plone-org please run jobs

2022-07-08 06:30 UTC, petschki requested changes
I'd recommend these changes for Plone 5.2 only.
Creating a new branch `1.6.x` here where this could be merged makes sense. For `master` branch (=Plone 6) I'd import the existing utility from `Products.CMFPlone.browser.search` and bump the version to `2.0.0dev0`

2022-07-08 06:39 UTC, petschki commented on plone/app/querystring/querybuilder.py
> +        query = query.replace(f'"{qp}"', "")
this doesn't work in py2

2022-07-08 06:40 UTC, petschki requested changes

2022-07-08 06:40 UTC, petschki commented on plone/app/querystring/querybuilder.py
> +        r.append(f'"{clean_qp}"')
not py2 compatible

2022-07-08 06:48 UTC, petschki commented
> For `master` branch (=Plone 6 only) I'd import the existing utility from `Products.CMFPlone.browser.search` and bump the version to `2.0.0dev0`

If this `munge_search_term` is used here too, maybe we should move it now to `plone.base` ? /cc @jensens

2022-07-08 06:52 UTC, erral commented
@jenkins-plone-org please run jobs

2022-07-08 08:05 UTC, mauritsvanrees requested changes
One inline comment for backwards compatibility on 5.2. Other than that it seems okay now.

We can go the route that @petschki says: create a branch for 5.2 with your current fix. I would say not 1.6.x but 1.x. And fix it on master for Plone 6 by importing the function from `CMFPlone`.

Or keep it on one branch, try to import from `CMFPlone`, and if it fails we define the function here.
Or try to import from `plone.base` if we move it there. Since it is used in two places, and it is Python-only code, `plone.base` makes sense to me. But Jens has a good feel for what is right to put in there.

2022-07-08 08:06 UTC, mauritsvanrees commented
The one remaining failing test on 2.7 is an unrelated robot failure that we can ignore. Has nothing to do with this PR.

2022-07-08 15:50 UTC, erral commented
Ok, I will change to be a method, create the 1.x branch for 5.2, port the change to master and bump it to 6 only

2022-07-08 16:13 UTC, erral commented
@jenkins-plone-org please run jobs

2022-07-08 16:15 UTC, erral commented
PR updated and PR for buildout.coredev also in place: https://github.com/plone/buildout.coredev/pull/805

2022-07-08 16:21 UTC, erral commented
@jenkins-plone-org please run jobs

2022-07-08 17:29 UTC, erral commented
@jenkins-plone-org please run jobs

2022-07-09 07:21 UTC, petschki commented
@jenkins-plone-org please run jobs

2022-07-09 07:27 UTC, petschki requested changes

2022-07-09 07:27 UTC, petschki commented on plone/app/querystring/querybuilder.py
> +    def munge_search_term(query):
`self` is missing as first parameter

2022-07-09 09:16 UTC, petschki commented
@jenkins-plone-org please run jobs

2022-07-09 10:06 UTC, petschki commented
@jenkins-plone-org please run jobs

2022-07-09 15:59 UTC, jensens commented
It could go to plone.base for Plone 6. I agree to branch away to 1.x and backport as done here.

2022-07-11 06:06 UTC, petschki approved these changes
LGTM

2022-07-11 06:07 UTC, merged