Fixes #111 for master and make it Plone 6 only
plone/plone.app.querystring pull request #113
Opened 2022-07-08 16:20 UTC by erral

As per comments in #112

2022-07-08 16:20 UTC, mister-roboto commented
@erral thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2022-07-08 16:20 UTC, erral commented
@jenkins-plone-org please run jobs

2022-07-09 07:23 UTC, petschki commented
@jenkins-plone-org please run jobs

2022-07-09 07:29 UTC, petschki requested changes

2022-07-09 07:29 UTC, petschki commented on plone/app/querystring/querybuilder.py
> -            query['SearchableText'] = self.munge_search_term(text)
I'd do the same way as for `1.x` keep the class method for better customization of the searchterm handling.

2022-07-09 07:29 UTC, petschki commented on plone/app/querystring/querybuilder.py
> -    def munge_search_term(self, q):
keep this and return:
```
    def munge_search_term(self, q):
        return munge_search_term(q)
```

2022-07-09 09:14 UTC, merged

2022-07-09 09:14 UTC, petschki commented
failing robot tests are unrelated